language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test
on:
    branch: master
deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local-dir: ./build
  on:
      branch: master